modLoader="javafml"
loaderVersion="[28,)"

[[mods]]
modId="wild_world"
version="1.5.0"
displayName="Wild World"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="FinMCPringles"
description='''
Adds various wild elements to your Minecraft world, as well as some late-game tech.
'''

[[dependencies.wild_world]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"



